### PR TITLE
Heroku Setup

### PR DESCRIPTION
**Pull request by jnielson94**
I moved a bunch of things around, but heroku is working for backend deploys 😄 

The frontend should still be able to deploy to firebase just fine, it'll just have to be done from inside the frontend directory (which you'd need to do in order to build the code anyway).

### CODE REVIEW

**Comment by garretthoffa** [comment]
I think the pull request looks good.

**Review by garretthoffa — COMMENTED** [review]
I think it looks good, I do have a question, would I need to include all of the dependencies from the routes/index.js if I create another routes file for get requests?

**Review by rgavinc — APPROVED** [review]
This looks great. Nice work on the readme, I didn't know it was that easy to deploy the app!

**Comment by jnielson94** [comment]
Unless anyone is opposed, I'm merging this in tomorrow morning (3/6) as a birthday present to myself 😛 @dylanmoh @gzapata90 @Cannonjc @jcwheatley haven't had any reactions to it (comments/approval), so I'm going to take their silence as a go ahead tomorrow 😉

**Comment by dylanmoh** [comment]
I just checked it out. Looks good, and happy birthday

**Pull request merged**
